### ISSUE TITLE
Комментарии по поводу проекта

### ISSUE THREAD

**Issue by Godofnothing** [DGAP-clicker-2020/clicker#15]
В целом, довольно качественно и грамотно организованный проект, удобочитаемый и модифицируемый код, с четким разделением целей и функционала для каждого файла. 

Про readme - было уже упомянуто ранее, так что 
 хорошим тоном будет сделать информативное описание и инструкцию по работе с проектом для стороннего пользователя. 

Хорошая практика - размечать цели и задачи в github issues!

Из небольших предложений по структуре проекта - вообще для settings лушче использовать  файл типа json или yaml, 

В связи с идентичностью интерфейса и функционала функций типа `create_shop_btn,  create_menu_btn` - так как создают `ui.Button` можно было реализовать в общем интерфейсе, но это так, по мелочи.

**Comment by sarseniy** [comment]
Спасибо за отзыв.

> Из небольших предложений по структуре проекта - вообще для settings лучше использовать файл типа json или yaml,

Хорошо, мы сделаем. Предложение перемещено в #16
