### ISSUE TITLE
Комментарии и предложения

### ISSUE THREAD

**Issue by kol060k** [DGAP-clicker-2020/clicker#22]
В целом классно, уронить игру не получилось (не обольщайтесь, я просто плохо старался :D).

Небольшой косяк в Readme: для запуска программы нужно перейти в code в директории clicker (ну раз уж вы совсем для дибилов писали :D)

Обнаруженные баги: 
1) После долгого отсутствия "You earned 0". Денег не накинули, так ещё и кружочек, на котором я закончил, отхилился. Кажется, обработка отсутствия пользователя где-то не работает :D
Также при выходе в меню и магазин здоровье кружочка не уменьшается, хотя я имею ненулевую afk power.
2) Периодически игра фризила с ошибкой `ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred`

Предложения (отсортированы по мере появления в голове):
1) Может быть сделать какие-то плашки для текста в menu? А то на фоне КПМ его не очень видно.
2) Может быть имеет смысл заменить однотонные кружки на что-то поинтереснее? Например, на рандомные первокурские учебники, лица преподов, ...
3) Можно добавить какой-то список игроков, которые заходили в игру, с краткой статистикой, потому что в первый раз я забыл, что ввёл, пришлось заново играть. Хотя, конечно, в таком случае нужно будет писать систему паролей, чтобы нельзя было попасть на чужой аккаунт.
4) Сюда же в аккаунты. Можете попробовать реализовать работу с буфером обмена и вставкой текста в поле ввода имени персонажа (сын Илона Маска рискует не поиграть в игру!)
P.S. не нужно реализовывать всё, просто вкинул. Тем более, до сдачи меньше недели.

**Comment by sarseniy** [comment]
Спасибо за отзыв. Отвечаю.

> После долгого отсутствия "You earned 0". Денег не накинули, так ещё и кружочек, на котором я закончил, отхилился.

Возможно afk_power было мало для текущей цели. До этого баг не был замечен, мы проверим.

> Также при выходе в меню и магазин здоровье кружочка не уменьшается, хотя я имею ненулевую afk power.

Да, в этот момент игра ставится на паузу.

> Периодически игра фризила с ошибкой

А какая ОС? Подобные проблемы вчера вылезали на занятии при запуске на Linux. На Windows такого не было.

Про про предложения подумаем. но реализацию не обещаем) Возможно допилим что-то в новом году. Сейчас добавляем кнопки регулировки музыки в меню.

**Comment by kol060k** [comment]
Система: Ubuntu 18.04
Специально проверил, что если оставить игру открытой, кружочек умирает быстро. Выходил перед моментом смерти кружочка, возвращался - видел его же, так ещё и с полным здоровьем :D

**Comment by sarseniy** [comment]
Действительно, при выходе из игры текущий прогресс не сохраняется, а урон "вне игры" начинает наносится по уже полностью здоровой цели. Для устранения этой механики необходима переработка логики подсчёта урона в АФК режиме, мы подумаем над этим. Пока могу посоветовать не выключать игру, если осталось мало ХП у цели)))

**Comment by sarseniy** [comment]
Кое-что добавили в финальную версию)

**Comment by kol060k** [comment]
Годнота подъехала, прям вообще очень круто стало :)
Расскажите, там за 5000$ та самая картинка с нк с рядом бутылок? Иначе просто нет смысла копить 5к на неё :D 
И что за загадочная матрёшка за 9999? Я сдохну столько выбивать :D

**Comment by sarseniy** [comment]
Про НК прямо в точку)

Ну а про матрёшку стыдно не знать https://youtu.be/n3Q_FIJ6s-s xD

**Comment by kol060k** [comment]
![image](https://user-images.githubusercontent.com/33592658/102013178-fb2eb480-3d67-11eb-8d0f-8fba67520a29.png)
Что я только что посмотрел
Пошёл копить
