### ISSUE TITLE
Exception при чтении файла

### ISSUE THREAD

**Issue by FrCln** [DGAP-clicker-2020/clicker#23]
![изображение](https://user-images.githubusercontent.com/54150197/101660716-85210980-3a58-11eb-89a7-9066c728507f.png)
Добавьте обработку таких исключений.

**Comment by sarseniy** [comment]
Это возникает из-за того, что у вас осталась старая версия данных, а сейчас в код были внесены изменения. Поправим.

**Comment by FrCln** [comment]
Из-за чего - это я понимаю, но надо учесть, что формат файла может оказаться не тот. Вдруг ещё чего-нибудь поменяете, опять всё сломается.
