### ISSUE TITLE
Баг с афк режимом

### ISSUE THREAD

**Issue by kol060k** [DGAP-clicker-2020/clicker#28]
Афк режим заработал, что-то он начисляет, время считает, я проверил.

Обнаружил баг: если сменить профиль, а потом сразу же зайти обратно в старый, то он покажет, что я отсутствовал 7 минут 14 секунд, начислит какое-то количество денег, а на входе здоровье учебника увеличится (видимо, связано это с тем, что он считает, что убил несколько учебников за те 7 минут):
![image](https://user-images.githubusercontent.com/33592658/102025173-aa42ae80-3daf-11eb-9847-2e3baa97020c.png)
За такое использование багов и дюп денег, я считаю, надо банить в кликере :D

Upd. Закрыл прогу на 5 секунд, вернулся, он верно написал, что я отсутствовал это время, и теперь при повторении действий, описанных выше, при смене профиля, программа утверждает, что я отсутствовал 5 секунд (и, соответственно, заработал 0). Видимо, дело в том, что при смене профиля время отсутствия не вычисляется, а подгружается последнее время, которое программа была выключена.

Upd. 2. Если AFK сила равна нулю, то при перезаходе сообщение о времени отсутствия почему-то не выводится вовсе (хотя, наверное, стоило бы, пусть даже заработано 0)

Upd. 3. Необязательно даже менять профиль. Достаточно просто нажать на change player и ввести то же имя.

Сейчас уже не тратьте время - скоро защита проекта. Но потом, если интересно, поправьте :)

**Comment by kol060k** [comment]
Upd. 4. Генератор наград в случае дюпа денег работает прикольным образом. Он начисляет 1$, затем 3, затем 10, затем 27, затем 74, а дальше круг замыкается. Держу в курсе.

**Comment by kol060k** [comment]
Upd. 5. Добил последние 2к$ с помощью найденной фичи, купил матрёшку. Спасибо, парни.
![image](https://user-images.githubusercontent.com/33592658/102025582-5daca280-3db2-11eb-8d96-8e15ea22e9d8.png)
Пытаюсь забыть имя профиля. Не получается.

**Comment by kol060k** [comment]
Upd. 6. После появления качественной музыки на фоне отпала необходимость пользоваться багом для фарма денег. Теперь можно кликать в удовольствие. Осталось накопить на задний фон с нк. Жду не дождусь, когда разработчики добавят нового контента в магазин <3

**Comment by kol060k** [comment]
Upd. 7.
![123](https://user-images.githubusercontent.com/33592658/102026677-8f286c80-3db8-11eb-957a-85d8333064ec.jpg)

**Comment by sarseniy** [comment]
Этот отзыв просто божественен! А баг мы пофиксили(

**Comment by sarseniy** [comment]
Мы вышлем вам коллекционную версию нашей игры (в одной из них будет ключ для Стима) xD
![image](https://user-images.githubusercontent.com/70952998/102065257-2245be80-3e1a-11eb-9a4b-cf08f2e284ba.png)

**Comment by kol060k** [comment]
Спасибо за оперативную работу и за клиентоориентированность!
Буду играть на стримах и рекламировать!
Жду DLC!

**Comment by sarseniy** [comment]
Да будет так.
